---
title: "Estimate regionwise Return Periods/Levels"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Estimate regionwise RP/RL}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---




```r
library(findpoolreg)
library(dplyr)
```
hi
As we have seen in the vignette about the bootstrap procedure, for
our simulated data set that comes with the package, we would reject the tiles
labelled 1,2, 3, 6 and 9.

A subsequent analysis could therefore be made on the pooled sample
consisting of the observations from those tiles with labels 4, 5, 7, 8.

A $T$-year RL that is estimated based on the GEV parameters estimated on the
pooled sample, has the interpretation that this value is expected to be exceeded
only once in $T$ years at each of the tiles that make up the pooling sample.
Therefore, a value that can be expected to be exceeded only once in $T$ years at
(at least) one of the tiles must be larger.

Similar things hold for the Return Period: an estimated return period of $T$ years
for a given event, obtained based on the fit of the GEV distribution to the pooled
sample, has the interpretation that one can expect one event of the same or larger
magnitude per tile per $T$ years.
Obviously, one would expect more than one event of similar magnitude happening in
the whole pooling region.


Exact values for these 'regional' return periods/levels are mathematically
hard to compute. We can, however, get a 'best estimate' based on a parametric
bootstrap estimate that accounts for the spatial dependence of the data.
This is what the function `get_regionwise_estimates` does.

First, we load the example data set again and subset the observations belonging
to our pooling region.


```r
data("example_data")
data("example_grid")
data("GMST")

pool_reg <- as.character(c(4,5,7,8))
pool_dat <- example_data[ , pool_reg]
pool_grid <- example_grid %>% dplyr::filter(Region %in% pool_reg)
head(pool_dat)
#>             4        5        7        8
#> [1,] 37.50947 22.06532 35.88537 27.67018
#> [2,] 24.43533 21.92437 19.31298 14.53100
#> [3,] 18.28184 24.79649 32.58503 33.16868
#> [4,] 20.64297 16.45135 17.59839 15.53414
#> [5,] 18.39849 17.84227 20.81810 28.08019
#> [6,] 22.83131 23.42914 23.52937 24.22438
head(pool_grid)
#> # A tibble: 4 x 7
#>   Region from_lat from_lon to_lon to_lat meanlon meanlat
#>    <int>    <dbl>    <dbl>  <dbl>  <dbl>   <dbl>   <dbl>
#> 1      4     45       2.25   4.25   46.2    3.25    45.6
#> 2      5     45       4.25   6.25   46.2    5.25    45.6
#> 3      7     46.2     2.25   4.25   47.5    3.25    46.9
#> 4      8     46.2     4.25   6.25   47.5    5.25    46.9

cvrt <- GMST$smoothedGMST[68:142]
```
We first compute estimates of the scale-GEV parameters based on the pooled sample.
The function `fit_scalegev` can take a data matrix as input and treat it as one
large sample.


```r
gev_pool <- fit_scalegev(pool_dat, temp.cov = cvrt, hessian = FALSE)
gev_pool
#> $mle
#>          mu       sigma       gamma       alpha 
#> 20.04274853  4.79035492  0.07577611  0.70297273 
#> 
#> $nll
#> [1] 3.199449
#> 
#> $conv
#> [1] 0
```
For example, we can now estimate the 100-year RL at reference climate of year 2021
based on these parameters.



```r
  ref21 <- (GMST %>% dplyr::filter( Year == 2021))$smoothedGMST
  tile_rl <- compute_rl(theta = gev_pool$mle, type = "scale", ref_gmst = ref21, Tyrl = 100)
  tile_rl
#> # A tibble: 1 x 3
#>      rl refGMST  Year
#>   <dbl>   <dbl> <dbl>
#> 1  47.9   0.925   100
```

Let's get an estimate of what return period an event with value 47.9381699, 0.925, 100 would
have for the whole pooling region. Further, we estimate the 'regionwise'
100-year at reference climate of year 2021. We base this estimate on `B = 10000`
bootstrap replicates (at home, better use an even larger value of $B$).
Note that `coords` must be a matrix containing a value of longitude and latitude
for each tile, so here we use the values of longitude and latitude of tile centres.


```r
reg_est <- get_regionwise_estimates(data = pool_dat, coords = as.matrix(pool_grid[ , 6:7]),
                                    temp.cov = cvrt, ref_gmst = ref21, B = 10000,
                                    r = tile_rl$rl, T.year = 100)
reg_est
#> $ecdf_max
#> Empirical CDF 
#> Call: ecdf_max <- stats::ecdf(maxis)
#>  x[1:10000] = 15.126, 15.723, 15.794,  ..., 90.615, 102.59
#> 
#> $rl_reg
#>  T = 100 
#> 54.88132 
#> 
#> $rp_reg
#> r = 47.9381698716152 
#>             32.36246 
#> 
#> $gev_par
#>          mu       sigma       gamma       alpha 
#> 20.04274853  4.79035492  0.07577611  0.70297273 
#> 
#> $fit_ms
#> $fit_ms$parhat
#>    cov11    cov12    cov22 
#> 1.106306 1.516044 2.768402 
#> 
#> $fit_ms$covmod
#> [1] "gauss"
```
We see that the region-wise return period for the event that is a 100-year event
per tile is approximately 32.4 years (component `reg_est$rp_reg`).
That means that the 100-year event
of a tile is expected to be exceeded once in 32.4 years in
at least one of the 4 regions.

An estimate of the region-wise 100-year RL, i.e. the value that is expected to be
exceeded only once in 100 years at any of the tiles, is given by 54.8813211
(component `reg_est$rl_reg`).

Since the empirical cdf of the bootstrap sample is returned, further values of
regionwise RLs /RPs can be computed.

E.g., the regionwise 50-year RL at reference climate of year 2021 is

```r
 quantile(reg_est$ecdf_max, p = 1-1/50)
#>      98% 
#> 50.53047
```
and the event of magnitude $r = 60$ has a return period of


```r
1/(1- reg_est$ecdf_max(58))
#> [1] 144.9275
```
years.
